_schema-version: '3.1'
ID: OpportunityRisks
version: 1.0.0
description: A simple CAP project.
parameters:
  deploy_mode: html5-repo
  enable-parallel-deployments: true
  subdomain: ts4tvklvn0st2fz4
build-parameters:
  before-all:
    - builder: custom
      commands:
        - rm -rf build/dist
        - mkdir -p build/dist
        - rm -rf build/ui-deployer
        - mkdir -p build/ui-deployer
    - builder: custom
      commands:
        - npm install --production
        - >-
          bash -c "cds -v | grep 'cds-dk' || npm i --production --no-save
          @sap/cds-dk"
        - bash -c "export PATH=$PATH:$(pwd)/node_modules/.bin"
        - cds build --production
  after-all:
    - builder: custom
      commands:
        - npm install
modules:
  - name: OpportunityRisks-db-deployer
    type: hdb
    path: gen/db
    parameters:
      buildpack: nodejs_buildpack
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: OpportunityRisks-service-uaa
      - name: OpportunityRisks-service-db
  - name: OpportunityRisks-srv
    type: nodejs
    path: gen/srv
    parameters:
      memory: 256MB
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
    build-parameters:
      builder: npm
      ignore:
        - node_modules
        - package-lock.json
    requires:
      - name: OpportunityRisks-service-uaa
      - name: OpportunityRisks-service-db
      - name: OpportunityRisks-service-destination
      - name: OpportunityRisks-service-metadata
      - name: OpportunityRisks-service-connectivity
      - name: OpportunityRisks-service-logs
  - name: OpportunityRisks-aux-destinations
    type: com.sap.application.content
    parameters:
      content:
        subaccount:
          existing_destinations_policy: update
          destinations:
            - Authentication: OAuth2UserTokenExchange
              Name: OpportunityRisks-service-uaa
              ServiceInstanceName: OpportunityRisks-uaa
              ServiceKeyName: OpportunityRisks-uaa-key
              sap.cloud.service: lcap.OpportunityRisks
            - Authentication: OAuth2UserTokenExchange
              Name: OpportunityRisks-app-srv
              TokenServiceInstanceName: OpportunityRisks-uaa
              TokenServiceKeyName: OpportunityRisks-uaa-key
              URL: ~{srv-api/srv-url}
              sap.cloud.service: lcap.OpportunityRisks
            - Name: OpportunityRisks-service-html5-apps-repo-host
              ServiceInstanceName: OpportunityRisks-html5-apps-repo-host
              ServiceKeyName: OpportunityRisks-html5-apps-repo-host-key
              sap.cloud.service: lcap.OpportunityRisks
            - Authentication: OAuth2UserTokenExchange
              Name: OpportunityRisks-OpportunityRiskService
              TokenServiceInstanceName: OpportunityRisks-uaa
              TokenServiceKeyName: OpportunityRisks-uaa-key
              URL: ~{srv-api/srv-url}/sap-crm-integration
              sap.cloud.service: lcap.OpportunityRisks
              sap.applicationdevelopment.actions.enabled: false
              sap.build.usage: CAP
              sap.processautomation.enabled: false
              HTML5.DynamicDestination: false
              WebIDEEnabled: false
              MobileEnabled: false
              AppgyverEnabled: false
            - Authentication: OAuth2UserTokenExchange
              Name: OpportunityRisks-OpportunityRisksService
              TokenServiceInstanceName: OpportunityRisks-uaa
              TokenServiceKeyName: OpportunityRisks-uaa-key
              URL: ~{srv-api/srv-url}/opportunity-risks
              sap.cloud.service: lcap.OpportunityRisks
              sap.applicationdevelopment.actions.enabled: false
              sap.build.usage: CAP
              sap.processautomation.enabled: false
              HTML5.DynamicDestination: false
              WebIDEEnabled: false
              MobileEnabled: false
              AppgyverEnabled: false
    build-parameters:
      no-source: true
    requires:
      - name: OpportunityRisks-service-uaa
        parameters:
          service-key:
            name: OpportunityRisks-uaa-key
      - name: srv-api
      - name: OpportunityRisks-service-html5-apps-repo-host
        parameters:
          service-key:
            name: OpportunityRisks-html5-apps-repo-host-key
      - name: OpportunityRisks-service-destination
        parameters:
          content-target: true
  - name: OpportunityRisks-launchpad
    type: html5
    path: build/launchpad
    build-parameters:
      builder: custom
      commands:
        - npm install
        - >-
          npx -p @ui5/cli@^3.0.0 ui5 build --dest dist
          --include-task=generateCachebusterInfo
        - bash -c "cd dist && npx bestzip ../../../build/dist/launchpad.zip *"
        - rm -rf dist
      _artifactName: launchpad.zip
      supported-platforms: []
      build-result: ../../build/dist
  - name: OpportunityRisks-aux-ui-deployer
    type: com.sap.application.content
    path: build/ui-deployer
    build-parameters:
      build-result: resources
      requires:
        - name: OpportunityRisks-launchpad
          artifacts:
            - launchpad.zip
          target-path: resources
    requires:
      - name: OpportunityRisks-service-html5-apps-repo-host
        parameters:
          content-target: true
resources:
  - type: org.cloudfoundry.managed-service
    name: OpportunityRisks-service-uaa
    parameters:
      service: xsuaa
      service-plan: application
      service-name: OpportunityRisks-uaa
      path: xs-security.json
      config:
        oauth2-configuration:
          redirect-uris:
            - https://${subdomain}.launchpad.${default-domain}/login/*
            - https://${subdomain}.${default-domain}/login/*
          credential-types:
            - binding-secret
            - x509
        xsappname: OpportunityRisks-${space}
        role-collections: []
  - type: org.cloudfoundry.managed-service
    name: OpportunityRisks-service-db
    parameters:
      service: hana
      service-plan: hdi-shared
      service-name: OpportunityRisks-db
  - type: org.cloudfoundry.managed-service
    name: OpportunityRisks-service-destination
    parameters:
      service: destination
      service-plan: lite
      service-name: OpportunityRisks-destination
      config:
        HTML5Runtime_enabled: true
        version: 1.0.0
  - type: org.cloudfoundry.user-provided-service
    name: OpportunityRisks-service-metadata
    parameters:
      service: metadata
      service-plan: standard
      service-name: OpportunityRisks-metadata
      config:
        default-domain: ${default-domain}
  - type: org.cloudfoundry.managed-service
    name: OpportunityRisks-service-connectivity
    parameters:
      service: connectivity
      service-plan: lite
      service-name: OpportunityRisks-connectivity
  - type: org.cloudfoundry.managed-service
    name: OpportunityRisks-service-logs
    parameters:
      service: application-logs
      service-plan: lite
      service-name: OpportunityRisks-logs
  - type: org.cloudfoundry.managed-service
    name: OpportunityRisks-service-html5-apps-repo-host
    parameters:
      service: html5-apps-repo
      service-plan: app-host
      service-name: OpportunityRisks-html5-apps-repo-host
